version: 2

requirements:
  signed_off_by:
    required: false

always_pending:
  title_regex: 'WIP|wip'
  explanation: 'Work in progress...'

always_approved:
  title_regex: 'NO REVIEW|SKIP REVIEW'
  explanation: 'This PR does not need approval'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^:\+1:|^LGTM|^\!\[LGTM|^lgtm|^Approved|^:sheep:|^\+1s|吼啊'
  reset_on_push:
    enabled: true

groups:
  util-review:
    required: 2
    conditions:
      labels:
        - util
    users:
      - at15
      - gaocegege
      - arrowrowe
      - ComMouse
  blog-review:
    required: 1
    conditions:
      files:
        - "source/*"
    users: all
